apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.name.namespace }}
  name: {{ .Values.global.name.appName }}
spec:
  type: {{ .Values.global.service.type }}
  {{- if eq .Values.global.service.headless true }}
  clusterIP: None
  {{- end }}
  {{- with .Values.global.name.appLabel }}
  selector:
    {{- toYaml . | nindent 8 }}    
  {{- end }}
  {{- range $ports := .Values.global.service.ports}}
  ports:
    - protocol: TCP
      port: {{ int $ports.port }}
      targetPort: {{ int $ports.targetPort }}
  {{ end }}
